apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb   # headless service is used for statefulset to create a stable network identity for each pod
    tier: db
spec:
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
  clusterIP: None  # headless service
  selector:
    project: roboshop
    component: mongodb
    tier: db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb       #service is used for external access to the mongodb statefulset
    tier: db
spec:
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port
  selector:
    project: roboshop
    component: mongodb
    tier: db
---    
apiVersion: apps/v1
kind: StatefulSet    #statefulset is used to manage the mongodb pods and provide stable network identity and persistent storage
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  selector:
    matchLabels:
      project: roboshop     #statefulset uses this selector to identify the pods it manages
      component: mongodb
      tier: db
  serviceName: "mongodb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        component: mongodb
        tier: db
    spec:
      containers:
      - name: mongodb
        image: aravindharla/mongodb:4.0.0
        volumeMounts:
        - name: mongodb
          mountPath: /data/db

  # PVC
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi        